name: Advanced Fund Screener

on:
  schedule:
    - cron: '0 12 * * SUN' # Runs every Sunday at 12:00 PM UTC
  push:
    branches:
      - main
    paths:
      - 'advanced_fund_screener.py'
      - '.github/workflows/fund_screener_workflow.yml'
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  run-screener:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          # 缓存键基于 Python 版本和脚本文件的 hash
          key: ${{ runner.os }}-python-${{ hashFiles('advanced_fund_screener.py') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          pip install --upgrade pip
          pip install pandas requests beautifulsoup4 lxml selenium webdriver-manager

      - name: Run Python script
        run: python advanced_fund_screener.py

      - name: Commit and push report
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Update advanced_fund_report.csv"
          file_pattern: "advanced_fund_report.csv"
