name: Detailed Fund Analysis Workflow

on:
  push:
    branches: [ main ]
    paths:
      - 'fund_detailed_screener.py'
      - '.github/workflows/fund_detailed_screener.yml'
  workflow_dispatch:

jobs:
  run-detailed-screener:
    runs-on: ubuntu-latest
    timeout-minutes: 359

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas numpy lxml urllib3 aiohttp

    - name: Run detailed screener script
      run: |
        python fund_detailed_screener.py | tee detailed_screener_output.log
      continue-on-error: true

    - name: Commit and push results
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add fund_details_enriched.csv detailed_screener_output.log
        git commit -m "Automated: Update detailed fund information and logs" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Archive logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: detailed-screener-logs
        path: detailed_screener_output.log
        retention-days: 7
