name: Fund Screener Workflow

on:
  push:
    branches: [ main ] # 推送至 main 分支时触发
  workflow_dispatch: # 允许手动触发

jobs:
  run-screener:
    runs-on: ubuntu-latest # 使用最新 Ubuntu 环境

    steps:
    - name: Checkout repository # 获取仓库代码
      uses: actions/checkout@v4

    - name: Set up Python # 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Python 3.10

    - name: Install dependencies # 安装所需库
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas numpy urllib3

    - name: Run fund screener script # 运行筛选脚本
      run: python fund_screener.py

    - name: Commit and push results # 提交结果文件
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add recommended_cn_funds.csv debug_fund_metrics.csv
        git commit -m "Automated: Update qualified funds list and debug info" || echo "No changes to commit"
        git push
