name: Fund Screener Workflow

on:
  push:
    branches: [ main ]
    paths:
      - 'fund_screener.py'
      - '.github/workflows/fund_screener.yml'
      - 'requirements.txt'  # 触发 requirements.txt 变更
  schedule:
    - cron: '0 2 * * *'  # 每天 UTC 2:00（北京时间 10:00）运行
  workflow_dispatch:  # 支持手动触发

jobs:
  run-screener:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 匹配优化版脚本运行时间（5-10 分钟）

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'  # 启用 pip 缓存（需要 requirements.txt）

    - name: Install Python dependencies and Playwright browsers
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          # 确保安装 playwright 而不是 selenium
          pip install requests pandas numpy urllib3 beautifulsoup4 tqdm efinance playwright
        fi
        # 使用 python -m 运行 playwright 模块以避免 "command not found"
        python -m playwright install chromium

    - name: Cache fund data
      uses: actions/cache@v4
      with:
        path: fund_data_cache
        key: fund-data-cache-${{ github.run_id }}
        restore-keys: |
          fund-data-cache-

    - name: Create cache directory
      run: mkdir -p fund_data_cache

    - name: Run fund screener script
      run: |
        python fund_screener.py | tee screener_output.log
      continue-on-error: true

    - name: Commit and push results
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add recommended_cn_funds.csv debug_fund_metrics.csv screener_output.log
        git commit -m "Automated: Update qualified funds list, debug info, and logs" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Archive artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: screener-artifacts
        path: |
          screener_output.log
          recommended_cn_funds.csv
          debug_fund_metrics.csv
        retention-days: 7
