name: Fund Screener Workflow

# 当以下事件发生时，触发此工作流
on:
  push:
    branches: [ main ] # 当代码推送到 main 分支时
  workflow_dispatch: # 允许你手动触发此工作流

jobs:
  run-screener:
    runs-on: ubuntu-latest # 在最新的 Ubuntu 运行环境中执行

    steps:
    - name: Checkout repository # 步骤1: 获取仓库代码
      uses: actions/checkout@v4

    - name: Set up Python # 步骤2: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # 指定 Python 版本

    - name: Install dependencies # 步骤3: 安装所需的 Python 库
      run: |
        python -m pip install --upgrade pip
        pip install pandas lxml html5lib beautifulsoup4
       

    - name: Run fund screener script # 步骤4: 运行你的 Python 脚本
      run: python fund_screener.py
      
    - name: Commit and push results # 步骤5: 将筛选结果提交回仓库
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add qualified_funds.csv
        git commit -m "Automated: Update qualified funds list" || echo "No changes to commit"
        git push
