name: Get Fund List

on:
  schedule:
    # 每天凌晨1点（UTC）运行，北京时间为上午9点
    - cron: '0 1 * * *'
  workflow_dispatch:
    # 允许手动触发

jobs:
  get-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests lxml

      - name: Run get_fund_list.py
        run: python get_fund_list.py

      - name: Commit and push fund codes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add fund_codes.txt
          git commit -m "Auto-update fund codes" || echo "No changes to commit"
          git push
